### ISSUE TITLE
Allow for multiple definitions of the same attribute

### ISSUE THREAD

**Issue by Hendekagon** [noprompt/garden#105]
AFAIA, Garden doesn't allow for defining multiple values of the same attribute, for example:

div { 
        image-rendering: -moz-crisp-edges;         /* Firefox */
        image-rendering:   -o-crisp-edges;         /* Opera */
        image-rendering: -webkit-optimize-contrast;/* Webkit (non-standard naming) */
        image-rendering: crisp-edges;
}

A workaround is to use spaces:

[:div {
                        "image-rendering" "-moz-crisp-edges"
                        " image-rendering" "pixelated"
                        }]

but it would be nice to be able to pass in a vector

[:div {
          :image-rendering [:-moz-crisp-edges :pixelated]
}]

**Comment by noprompt** [comment]
Please see #6. You can also use the `{:prop #{val-1 val-2 ...}}` syntax.

**Comment by noprompt** [comment]
We need to get this into the documentation.

**Comment by Hendekagon** [comment]
ok, wasn't aware of that
