### ISSUE TITLE
Apply pseudo-class WITHOUT space

### ISSUE THREAD

**Issue by WorldsEndless** [noprompt/garden#111]
For the life of me I can't figure out how to produce

    div.row:nth-child(even)

instead of what I keep getting

    [:div.row {:display "table-row"}
     [(nth-child :even) {:background-color (ycolors :blue5)}]]
    ;; div.row :nth-child(even)

How should nth-child be used so it doesn't produce the space, with which it cascades to all children?

**Comment by noprompt** [comment]
@WorldsEndless Have you tried implementing your own selector type?

**Comment by WorldsEndless** [comment]
I'm not sure what is meant by that; probably I'm needing to read a section of the documentation? In any case, it seems problematic that spaces are always interpolated when it changes the semantics of the rules.

**Comment by WorldsEndless** [comment]
I was able to achieve the desired result with the following: 
`   [:> [(nth-child :even) {:background-color (ycolors :blue10)}]]`
