### ISSUE TITLE
Defstyles with Vendors?

### ISSUE THREAD

**Issue by WorldsEndless** [noprompt/garden#112]
I think there's a hole in my understanding here, but here goes. 

I'm using Luminus with lein garden for auto-compilation. My project points to styles.clj/main, which is defined with defstyles. I have a preamble map in defstyles that includes :vendors, and if I use the repl to run (apply garden.core/css main) I get exactly what I want, namely, an output css file that includes all the vendor information for my css animation. 

Problem: lein garden (and presumably a fresh run of lein run) doesn't seem to do an (apply css main) on my style; instead, it generates something with none of the vendor information. What is it I need to do to get vendor information to be respected in the output of lein garden auto? (sorry if this is the wrong place; I'm really not sure if this is a problem with defstyles or with lein garden).

**Comment by hkjels** [comment]
With `lein` you can specify a vendor-list in your project-manifest. I see that this issue is really old, so you probably found the solution I guess. Feel free to close this one
