### ISSUE TITLE
seconds unit dropped for :animation when pretty print turned off when magnitude is X.0

### ISSUE THREAD

**Issue by thedavidmeister** [noprompt/garden#119]
I tried this:

`{:animation [[:my-keyframes (u/s 3.0) :infinite :ease-in-out]]}`

Works with pretty print turned off, but when it is turned on, the `s` for `3.0s` gets dropped.

Changing the magnitude from `3.0` to `3` or `3.5` works. Seems like anything that ends in `.0` drops the `s` when compiled without pretty print.

**Comment by thedavidmeister** [comment]
`:transition` seems to have the same problem, so i don't think it has anything to do with the rule, just the way units are handled.

**Comment by noprompt** [comment]
@thedavidmeister Thanks for opening up all of these issues. It would really help if you gave me some steps to reproduce. I need more than a snippet. I need the _exact_ code that failed and what you expected the result to be.

**Comment by RadicalZephyr** [comment]
Not sure if you still need more to reproduce this issue, but I just noticed it as well.

``` clojure
(defstyles screen
    [:.test
   {:thing "10.0s"
    :two "10s"}])
```

produced:

``` css
.test {
    thing: 10.0;
    two: 10s
}
```

where it should have been:

```css
.test {
    thing: 10.0s;
    two: 10s
}
```
(note the additional "s" in the value of the `thing` property)

**Comment by rafd** [comment]
Seems to also be an issue with non-animations:

```
(garden/css {:pretty-print? false} [:body {:font-size "1.0em"}])
```

Gives:
```
body{font-size:1.0}
```

Which is not valid.

It seems this is a YUI compressor issue: https://github.com/yui/yuicompressor/issues/322

My workaround has been to do: `1.00001em`

**Comment by opqdonut** [comment]
bumped into this same issue with px:
```
(g/css {:pretty-print? false} (list [:foo {:bar (u/px 1200.0)}]))
```
generates
```
foo{bar:1200.0}
```

**Comment by pavel-klavik** [comment]
This bug is very annoying because it is not something one suspects. While the long term solution of cutting YUI can be great, it would be great to add a quick hack which would fix it. It should be enought to add a check when converting maps describing units into strings whether the value is a float which is actually an integer, and if so, to automatically convert it into int. Something like this:

```clojure
(if (and (float? value) (== value (int value))
  (int value)
  value)
```

**Comment by noprompt** [comment]
@pavel-klavik Are you able to submit a patch for this? If your proposal works to solve the issue, I'm happy to merge it.

**Comment by pavel-klavik** [comment]
This should work, tested in REPL. I am not sure how to actually build Garden for development, so it would be great if someone can test it fully or maybe adding automatic tests??
