### ISSUE TITLE
0 percentage keyframe keywords lose the % symbol when pretty print turned off

### ISSUE THREAD

**Issue by thedavidmeister** [noprompt/garden#120]
I tried:

`[:0% :50% :100% {:transform "scale(0.0)"}]`

Worked as expected with pretty print turned on.

With pretty print turned off, the `%` from `0%` was dropped, which caused the whole keyframe rule to do nothing.

Using strings like `"0%"` instead of keywords like `:0%` seemed to workaround the issue.

**Comment by thedavidmeister** [comment]
Wait, no, I was wrong. Strings do not help, the `%` for `0%` is dropped always, breaking keyframes.

**Comment by noprompt** [comment]
@thedavidmeister Is that with or without minification? This seems eerily familiar to #116 that had a similar problem.

**Comment by levitanong** [comment]
Is using `:from` in place of `:0%` a sufficient workaround?

**Comment by luontola** [comment]
I noticed a similar bug with colors. 

```clj
(css {:pretty-print? false} [:.example {:color  (saturate "#ccc" -10)}])
```

This produces the following output, about which Chrome gives the error "Invalid property value".

```css
.example{color:hsla(0,0,80%,1.0)}
```

The correct result would be:

```css
.example{color:hsla(0,0%,80%,1.0)}
```

**Comment by noprompt** [comment]
I'd really appreciate any help resolving this issue. I'm really busy with work, family, and other things at the moment and it's hard for me to make time to solve this problem on master.
