### ISSUE TITLE
Vendor support for IE and Edge

### ISSUE THREAD

**Issue by stephenway** [noprompt/garden#122]
I'm trying to work with flexbox on garden and cannot provide a fallback `:display  "-ms-flexbox"` because I'm already specifying the display property for modern browsers. It would be nice if I could add `ms` to vendors and get that extra rule added for every property that needs it.

**Comment by noprompt** [comment]
@stephenway You can provide more than one display property. Both

```clj
[:x
 {:display #{:flexbox :-ms-flexbox}}]
```
and
```clj
[:x
 {:display :flexbox}
 {:display :-ms-flexbox}]
```
will compile to
```css
x {
  display: flexbox;
  display: -ms-flexbox;
}
```

**Comment by dcostaras** [comment]
If anyone comes across this needing to use the set form for fallback values (e.g. [Ornament](https://github.com/lambdaisland/ornament) will merge the maps into one before passing to Garden) but for a property where order matters (e.g. width; both values will be valid in supported browsers) then you can use [ordered sets](https://github.com/clj-commons/ordered#sets).
