### ISSUE TITLE
space-join should support units

### ISSUE THREAD

**Issue by binarykitchen** [noprompt/garden#129]
Something like this does not work

```
:animation [[<some animation> (space-join [(s 1.4) "ease-in-out" "infinite"])]]
```

It produces exception `garden.types.CSSUnit cannot be cast to java.lang.Number`

**Comment by noprompt** [comment]
This doesn't look like a problem with `space-join`. What's `(s 1.4)`? `1.4` is the only `java.lang.Number` I see in the picture.

**Comment by binarykitchen** [comment]
never mind, figured out you can do it better with double `[` like
`{:animation [[spinner-rotator (s 1.4) "linear" "infinite"]]}`

ps: s is the unit for second
