### ISSUE TITLE
Translating :checked and +

### ISSUE THREAD

**Issue by WorldsEndless** [noprompt/garden#131]
I can't seem to figure out how to generate this selector: 

`.onoffswitch-checkbox:checked + .onoffswitch-label`

I've tried variations, e.g.
`(garden.core/css [:div [:&s/checked {:foo :bar}]])`

`(garden.core/css [:div (s/checked) {:foo :bar}])`

but no luck. A little help?

**Comment by WorldsEndless** [comment]
This is the closest I've come, but the :checked is in the wrong place:

```
(garden.core/css [(s/+ (s/checked :.onoffswitch-checkbox) :.onoffswitch-label) {:background-color 'white}])
:checked.onoffswitch-checkbox + .onoffswitch-label {
  background-color: white;
}
```

**Comment by WorldsEndless** [comment]
Almost got it... 

```
(garden.core/css [(s/+  (s/checked :onoffswitch-checkbox)
                                    :.onoffswitch-label) {:background-color 'white}])
:checkedonoffswitch-checkbox + .onoffswitch-label {
  background-color: white;
}
```

**Comment by hkjels** [comment]
I'm pretty sure this works:
```Clojure
[(s/+ :.onoffswitch-checkbox:checked :.onoffswitch-label) {}]
```

Also, if you don't need to do anything programatically to the selector, you can actually use the string-variant.

**Comment by WorldsEndless** [comment]
Thanks! What do you mean the "string-variant"?

**Comment by hkjels** [comment]
```clojure
[".onoffswitch-checkbox:checked + .onoffswitch-label" {}]
```

**Comment by hkjels** [comment]
Note that I think #127 applies to `(s/+)` as well as `(s/>)`, so the combination of `(s/&)` and `(s/+)` might not work

**Comment by WorldsEndless** [comment]
I had no idea of that "string variant"! That completely changes my converting-css-to-Garden life!
