### ISSUE TITLE
garden + hiccup dead code elimination

### ISSUE THREAD

**Issue by JAremko** [noprompt/garden#132]
Is there a common way to track what html hiccup generates and then use this data to make garden output only used css(only for actually outputted DOM elements)?

**Comment by Harleqin** [comment]
That seems difficult to do in a general way, since hiccup can (and usually does) interleave arbitrary code.  You would have to analyze every possible code path for strings and symbols that might become parts of CSS selectors.

**Comment by noprompt** [comment]
@JAremko Not that I'm aware of but I don't think you need to go that far. Prior to handing your hiccup to the `html` macro you could walk through it collecting any information you need. Here's a quick and dirty sketch for retrieving all of the (potential) tag names.

```clj
(ns scratch
  (:require [clojure.walk :as walk]))

(let [hiccup [:body
              [:header
               [:h1.page-title
                "..."]]

              [:div#footer
               [:div
                [:h3
                 "..."]
                (for [item ["foo" "bar" "baz"]]
                  [:ul
                   [:li
                    [:span item]]])]]]

      tags (volatile! #{})

      _ (walk/prewalk
         (fn [x]
           (when (vector? x)
             (vswap! tags conj (first x)))
           x)
         hiccup)]
  @tags)
;; #{:ul :div#footer :li :header :h1.page-title :div :h3 :body :span}
```
It's not a serious solution by any stretch of the imagination but it's enough to get you in the right direction.

**Comment by hkjels** [comment]
You might also want to draw inspiration from `elm-css`. There it goes the other way around, classes have to be defined in the css in order to use them in the "markup"
