### ISSUE TITLE
Official Web Site for Garden

### ISSUE THREAD

**Issue by groundedsage** [noprompt/garden#133]
I have been communicating with @noprompt about the future of Garden. He has a few announcements to make to the community at large so I won't steal his thunder.

Long story short the community needs to step up and become stewards of this project.

I have offered to create an official website for Garden. For this we need to really show off Garden and it would be great to both have the community put forward their ideas as to what would be the best way to show off Garden to the rest of the world and also put together some case studies of companies that are using Garden in production to show it has real world value. 

I propose that we create a basic landing page and use something like [Typeform](https://www.typeform.com/) to survey people and companies that are using Garden. This is something that the Clojure community could then share in a Tweet. Allowing us to capture valuable information for the development of this website and project. 

### What I would like is ideas about what we should ask in the survey

**Comment by noprompt** [comment]
@GroundedSage I've provided you with access [here](https://github.com/garden-clojure/garden-clojure.github.io). Have at it!

🌹

**Comment by noprompt** [comment]
@GroundedSage I'm not sure what should be on the survey though.

**Comment by GroundedSage** [comment]
Cool. I will get a start on this hopefully next week :)

**Comment by GroundedSage** [comment]
![frame](https://cloud.githubusercontent.com/assets/11351767/26293145/d008ac9a-3efe-11e7-9604-140b444a3ad7.png)

This is the kind of idea I have for a logo.

**Comment by GroundedSage** [comment]
Questions I have put into typeform:

1. Have you used Garden in your projects?
2. If NO what is holding you back from using it?
3. Are you interested in maintaining Garden and/or ensuring it's longevity?
4. Please tell us your Name or your Business Name
5. Please share your email if you are happy for us to contact you regarding your answers to this survey
6. Would you be willing to sponsor Garden through Open Source Collective?
7. Please share any cool projects you have used Garden for or others you have found that could be used as Case Studies on this website.

**Comment by GroundedSage** [comment]
I pushed a really rought draft version. Just a hack together of the current template setup I have for doing other websites. It seems it needs to be set up with a different branch name when not using a pre-built template?

**Comment by noprompt** [comment]
@GroundedSage This is a great start! Even if it's a rough draft, having started something is so much more than we had before.

> It seems it needs to be set up with a different branch name when not using a pre-built template?

What's this about?

**Comment by noprompt** [comment]
@GroundedSage Also, we should continue these discussions over in the issue tracker for the website repo. We can leave this open in case anyone else wants to chip in on the discussion.

**Comment by GroundedSage** [comment]
@noprompt appears to be working now. Page wasn't working and I somehow ended up reading some information which told me we needed some specific branch name.
