### ISSUE TITLE
Broken cssfn's in v2.0

### ISSUE THREAD

**Issue by hkjels** [noprompt/garden#135]
I've trimmed most of my garden to `v2.0.0-alpha1`, but Garden-functions like the ones returned from `defcssfn` breaks with the following exception:
`java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Keyword`

**Comment by noprompt** [comment]
@hkjels I've addressed the problem in the commit 8c6d040. In the future can you give me a bit more than exception?

Thanks for reporting the bug.

**Comment by hkjels** [comment]
Woa! Great!
Yeah, I've wanted to get more familiar with the inner workings, so you might get a pull-request next time if that's preferable?

**Comment by noprompt** [comment]
@hkjels It's always helpful but there's definitely no pressure! If you're not sure about something, please ask.
