### ISSUE TITLE
Launch garden auto from the repl

### ISSUE THREAD

**Issue by WorldsEndless** [noprompt/garden#141]
Now that I'm getting used to component lifecycles (actually, I lie; it's Mount), I like to launch everything from the REPL with things like (mount.core/start). Is there a way to start/stop the garden auto process from the REPL, so I don't need to step back to the terminal for this? 

As an aside, Garden is a fantastic project and idea. I'd be happy to contribute what time I can. Am I supposed to create a separate post for that?

**Comment by priyatam** [comment]
You will have to include lein-garden and call [this](https://github.com/noprompt/lein-garden/blob/master/src/leiningen/garden.clj#L122) function from component/mount.

**Comment by WorldsEndless** [comment]
For future reference: This project does the job wonderfully https://github.com/Otann/garden-gnome
