### ISSUE TITLE
Garden 2.0.0 is not accessible from clojars or maven central

### ISSUE THREAD

**Issue by Ihromant** [noprompt/garden#142]
Hi everyone,

Garden looks nice and there are new features and fixes in 2.0.0. But it is not accessible from Clojars or Maven Central. Are there plans to push it there? Or there is some other way to resolve this problem?

**Comment by hkjels** [comment]
I'm not sure which issue it's mentioned, but it was said that until `clojure.spec` becomes stable you'll need to clone the repo and install manually. That will make it accessible to your local project. Hope that helps

**Comment by noprompt** [comment]
@Ihromant: As @hkjels mentioned, until `clojure.spec` stabilizes I am not open to pushing a `SNAPSHOT` version or otherwise of the next major release of this library. Of course, you are always welcome to fork/clone this library and install/release your own artifact for your needs.
