### ISSUE TITLE
defcssfn docs missing

### ISSUE THREAD

**Issue by AndreaCrotti** [noprompt/garden#143]
I was trying to use `url` in CSS and could not find out how to do it with Garden.
Then looking in the whole repo here I found an example of `defcssfn` that was defining exactly `url`.

However there is no mention of this in the README, maybe it would be worth mentioning that?
Thanks for the great library by the way, CSS is almost fun!

**Comment by noprompt** [comment]
Hi @AndreaCrotti, thanks for the feedback. In my free time I am busy with other things at the moment and haven't made time to offer more support to this library. If you are able to submit a doc patch I would be happy to review it.
