### ISSUE TITLE
How to use `nth-child` in garden? Are there any examples?

### ISSUE THREAD

**Issue by cmal** [noprompt/garden#147]
Hi! How to use `nth-child` pseudo-class in `garden`?

I found it need a extra `n` parameter but don't know how to write it after `:&:`.

I tried `:&:nth-child(4)` and `:&:(nth-child 4)`, both failed.

**Comment by rap1ds** [comment]
Like this:

```clj
user> (require '[garden.core :refer [css]])
nil
user> (require '[garden.selectors :refer [& nth-child]])
nil
user> (css [:div {:color :blue} [(& (nth-child 4)) {:color :red}]])
"div {\n  color: blue;\n}\n\ndiv:nth-child(4n) {\n  color: red;\n}"
```

**Comment by cmal** [comment]
Thank you!

**Comment by cmal** [comment]
Hi, sometimes I use `&` I got this:

`IllegalArgumentException: No method in multimethod 'parse' for dispatch value: &`
