### ISSUE TITLE
How to set pseudo element CSS such as `input::placeholder`?

### ISSUE THREAD

**Issue by cmal** [noprompt/garden#148]
How to set pseudo element CSS such as `input::placeholder` in garden?
Does garden support this?

**Comment by hkjels** [comment]
https://github.com/noprompt/garden/wiki/Syntax#selectors

**Comment by cmal** [comment]
Hi, I think the selectors such as `before`, `after` and so on are defined in https://github.com/noprompt/garden/blob/master/src/garden/selectors.cljc by the `defpseudoelement`s, but `placeholder` is not in the list of `defpseudoelement`s, so I doubt it cannot work in garden.

**Comment by minikomi** [comment]
You can use the same technique to define your own.
eg. with `garden.selectors` required as `gs`:

```clj
(gs/defpseudoelement placeholder)

(def email-input-styles
  [:input.email
   [(gs/& placeholder)
    {:color "#aaff22"}]])
```

Will produce css such as:

``` css
input.email::placeholder {
  color: #aaff22;
}
```

**Comment by cmal** [comment]
Thank you @minikomi . It works.
