### ISSUE TITLE
Using CSS variables

### ISSUE THREAD

**Issue by ampersanda** [noprompt/garden#157]
I am trying to use Garden, but I have a problem when I was going to store variable inside Garden
which code below
```
(defstyles style
           [::root {:--test "#000"}]
           [:body {:margin 0}]
           [:h1 {:font-size "20px"
        :color "var(--test)"}])
```
produce 
```
root {
  --test: #000;
}

body {
  margin: 0;
}

h1 {
  font-size: 20px;
  color: var(--test);
}
```

So, I am glad to know how to properly use `:root` inside Garden?

Thank you

**Comment by hkjels** [comment]
You can just use regular `let` or `def` or is there a particular reason you need it to be css-vars?

**Comment by ampersanda** [comment]
Oh, I see, I forgot about it. Thank you

**Comment by ampersanda** [comment]
@hkjels : I realized that I be able to update CSS variables via Javascript/Clojurescript by `document.documentElement.style.setProperty('--test', "10px")`, Is there any solution for it whan I use garden?

**Comment by b3n** [comment]
To your point @hkjels, CSS lets you change a variable based on a media query, for example
```
:root {
  color-scheme: light dark;
  --color-page-background: #fff;
}

@media (prefers-color-scheme: dark) {
    :root {
        --color-page-background: #000;
    }
}

body {
    background: var(--color-page-background);
}
```

Is there a similar equivalent using a regular `let` or `def`?

**Comment by KyleErhabor** [comment]
This is an old issue, but you can use custom properties:
```clojure
(ns my.ns
  (:require
    [garden.core :refer [css]]
    [garden.selectors :as s]))

(css [[(s/root) {:--text-color "red"}]
      [:p {:color "var(--text-color)"}]])
;; :root {
;;   --text-color: red;
;; }
;; 
;; p {
;;   color: var(--text-color);
;; }
```
Personally, I use them to not have to sprinkle my color palette around my codebase (I *just* need Garden for creating CSS in Clojure), but they have other advantages, like how you'll need media queries less for normal properties (e.g. setting a standard light vs. dark mode color) and their ability to be manipulated in JavaScript as one source.
