### ISSUE TITLE
Link broken for Tutorial and example in Wiki

### ISSUE THREAD

**Issue by wontheone1** [noprompt/garden#174]
http://www.webp.ch/fourre-tout/target/#!/dgellow.fourre_tout.garden

^ this link does not shows anything.

**Comment by noprompt** [comment]
@wontheone1 are you not able to edit the wiki and remove/change the link?

**Comment by wontheone1** [comment]
@noprompt I just came to this repo to try out garden for the first time. I don't know what is the correct link, so I can't change it.
Also I am not comfortable deleting link outright because it might be better to put correct link than deleting it for the new comers like myself.

**Comment by wontheone1** [comment]
Ideally I wish there was a code example. It seems like the convenient way to use garden is use `lein-garden` to auto compile but I really didn't have any idea how others use garden (typical work flow) and just trying to make my best guess.

**Comment by noprompt** [comment]
@wontheone1 I see. I don’t know anything about the link myself but maybe the contributor who added the link could help with this. We could @ them in this thread and see if they respond. If not, then I think removing the link would be warranted.

**Comment by wontheone1** [comment]
@dgellow History shows that you added link to the wiki, could you fix the broken link ?

**Comment by dgellow** [comment]
Hello there. I updated the wiki page, the corrected link is https://dgellow.dev/fourre-tout/target/#!/dgellow.fourre_tout.garden.
