### ISSUE TITLE
how to supply the value to grid-template-area?  in css it is multiple strings...

### ISSUE THREAD

**Issue by ftravers** [noprompt/garden#176]
in css a grid-template-area can have a value like:

```
    grid-template-areas: 
      ".  .  hd hd   hd   hd   hd   hd   ."
      "sd sd sd main main main main main main"
      "sd sd sd  ft  ft   ft   ft   ft   ft";
```

how should we represent this in clojurescript?  I tried putting it in a vector like:

```
:grid-template-areas
     [".  .  hd hd   hd   hd   hd   hd   ."
      "sd sd sd main main main main main main"
      "sd sd sd  ft  ft   ft   ft   ft   ft"]
```
Thoughts?

**Comment by roosta** [comment]
It ain't pretty but try this:
```clojure
{:grid-template-areas
 [["'.  .  hd hd   hd   hd   hd   hd   .'"
   "'sd sd sd main main main main main main'"
   "'sd sd sd  ft  ft   ft   ft   ft   ft'"]]}
```
The surrounding vectors denote that the elements should be space separated, while a single vector would comma separate.
Got it to work in a local example.

**Comment by ftravers** [comment]
thank you @roosta.  I ended up with another solution that'll I'll share here too:

**Comment by roosta** [comment]
Glad you worked it out :)
