### ISSUE TITLE
Property order is different in output CSS, renders incorrectly in browser

### ISSUE THREAD

**Issue by Jarzka** [noprompt/garden#180]
Hi

I noticed the following problem when generating CSS from a Clojure map:

```
(garden.core/css [:body {:font-family "open_sans, Verdana, Helvetica, sans-serif"
                         :color "#121212"
                         :background "black url('/images/background2.jpg')"
                         :background-repeat "no-repeat"
                         :background-position "center"
                         :background-attachment "fixed"
                         :background-size "cover"
                         :margin 0
                         :padding 0}])
```

It generates the following CSS:

```
body {
    background-position: center;
    background-attachment: fixed;
    background-repeat: no-repeat;
    font-family: open_sans, Verdana, Helvetica, sans-serif;
    margin: 0;
    padding: 0;
    background-size: cover;
    background: black url('/images/background2.jpg');
    color: #121212;
}
```

The order of properties has changed. This sould not be a problem in most cases, but in this case it is, because it seems that browser ignores background position values if the background is not defined first.

Here is a proof of this (repeats in Firefox & Chrome)
https://jsfiddle.net/75byvs96/ --> Background defined last, render incorrectly (position properties are ignored)
https://jsfiddle.net/75byvs96/1/ --> Background defined first, renders correctly.

**Comment by Jarzka** [comment]
I solved this by using `sorted-map`.

**Comment by harold** [comment]
Interesting! Never thought about this (Clojure map keys are unordered, so this makes sense)

In this case `sorted-map` helps because you happen to want alphabetical order. :smile:

**Comment by Jarzka** [comment]
Yes, in this case it works. However, if at some point I would need to define property order fully manually, this might be a bit problematic.

**Comment by Jarzka** [comment]
Would it be possible to define style map as a vector in that case?

**Comment by Jarzka** [comment]
I also noticed that his is probably a problem only when using shorthands, as:

> As with all shorthand properties, any omitted sub-values will be set to their initial value.

So, if I use `background-color` and `background-image` the order does not matter.

**Comment by noprompt** [comment]
FYI you can also use more maps if the order of properties is relevant:

```clj
(garden.core/css
 [:body
  {:font-family "open_sans, Verdana, Helvetica, sans-serif"
   :color "#121212"}
  {:background "black url('/images/background2.jpg')"}
  {:background-repeat "no-repeat"}
  {:background-position "center"}
  {:background-attachment "fixed"}
  {:background-size "cover"}
  {:margin 0
   :padding 0}])
```
Compiles to
```css
body {
  font-family: open_sans, Verdana, Helvetica, sans-serif;
  color: #121212;
  background: black url('/images/background2.jpg');
  background-repeat: no-repeat;
  background-position: center;
  background-attachment: fixed;
  background-size: cover;
  margin: 0;
  padding: 0;
}
```

This used to be documented in the README but then all the stuff was moved from the README to the Wiki and then only partially back to the README. 🙄
