### ISSUE TITLE
Question about defining multiple style maps

### ISSUE THREAD

**Issue by Jarzka** [noprompt/garden#184]
Hi

As I understand the Garden selector syntax, it has the selector part (first N elements which can be strings, keywords or vectors) and the style map should be the last element in every vector.

However, if I have something like this:

```cljs
(garden.core/css [:h1 {:font-weight "normal"} {:font-weight "bold"}])
```

it outputs this CSS:

```css
h1 {
    font-weight: normal;
    font-weight: bold;
}
```

Is this the designed behavior? Are multiple style maps supported like this or what does it mean to have multiple style maps as part of the vector? Also, does Garden assume that maps are always CSS properties, never part of the selector?

**Comment by Jarzka** [comment]
I'm mainly asking this because I'm planning creating a simple algorithm which will automatically scope a Garden selector to specific class. This is possible to do by simply wrapping the style map in the selector within a vector. For example from `[:h1 {:font-weight "normal"}]` to `[:h1 [:.my-custom-scope {:font-weight "normal"}]]`. I'm just curious to know if I can safely do this.

**Comment by Jarzka** [comment]
I think having multiple style maps in a single Garden vector is allowed, but usually you want to put them in a different context, like:

```clj
 [:.outer {:font-weight "normal"}
  [:.inner {:font-weight "bold"}])
```

**Comment by harold** [comment]
It does appear that the compiler (at least in the version we're using, `"1.3.10"`) allows multiple declerations in a single rule:

https://github.com/noprompt/garden/blob/16a390186fea989e8049c00cd57f9bdd82a22fd3/src/garden/compiler.cljc#L492-L502

`render-css` supports many sequential types:

https://github.com/noprompt/garden/blob/16a390186fea989e8049c00cd57f9bdd82a22fd3/src/garden/compiler.cljc#L658

Accounting for this in your programmatic manipulations of garden data seems like a good idea.

Note: I'm mostly just a user of this library, still learning more about the internals myself, so take my advice w/ a grain of salt.

**Comment by noprompt** [comment]
> Is this the designed behavior? 
Yes
> Are multiple style maps supported like this or what does it mean to have multiple style maps as part of the vector?
It means merge them all into one set of declarations from left to right. This is to both address problems with ordering in large Clojure maps and ordering of declarations in CSS.
> Also, does Garden assume that maps are always CSS properties, never part of the selector?
Yes.

**Comment by Jarzka** [comment]
Thanks for the answers.
