### ISSUE TITLE
Warning about `garden.color/abs` shadowing `clojure.core` output when using Clojure 1.11.0

### ISSUE THREAD

**Issue by stevejmp** [noprompt/garden#194]
## Expected
In a project using Garden, bumping the Clojure dep to the recent release, `1.11.0`, should output no new warnings or exceptions when run.

## Actual
```
WARNING: abs already refers to: #'clojure.core/abs in namespace: garden.color, being replaced by: #'garden.color/abs
```

## Steps to Reproduce
1. In a project using Garden, bump the Clojure dep to `1.11.0`
2. Run the project in a terminal
3. View the output

## Versions
Garden `master` 90bf058 (2022-02-05)
Clojure 1.11.0
Java 11.0.14
Leiningen 2.9.8

## More Info

A new `abs` function was added to `clojure.core` in `1.11.0`. The `garden.color/abs` function now shadows this, resulting in the warning.

**Fix**: add `abs` to the `(:refer-clojure :exclude` vector in `garden.color`.

PR incoming.

**Comment by aldebogdanov** [comment]
Garden `1.3.10`. Warning remains
