### ISSUE TITLE
content: " " produces wrong output

### ISSUE THREAD

**Issue by StarScape** [noprompt/garden#200]
It is often desirable to set the `content` property of a elements `::before` or `::after` psuedoelements to " ", but this breaks in Garden, producing a blank space instead of `" "`:

```clojure
(css [:.foo::after {:content " "}])
=> ".foo::after {\n  content:  ;\n}"
```

A workaround: `{:content "\" \""}`

**Comment by harold** [comment]
Interesting, out of curiosity what version of clojure and garden are you using?

For me, on clojure `1.10.3`, `:.foo::after` is not a valid keyword.

```
> :.foo::after
Syntax error reading source at (REPL:21:1).
Invalid token: :.foo::after
```

**Comment by Outrovurt** [comment]
> Interesting, out of curiosity what version of clojure and garden are you using?
> 
> For me, on clojure `1.10.3`, `:.foo::after` is not a valid keyword.

I strongly suspect the OP is using ClojureScript, where bizarrely enough it is actually a valid keyword, as I've only just discovered myself.

I'm not 100% certain but I believe the recommended way to emit quotes is to use `garden.util/wrap-quotes`, for example:

```clojure
(css [".foo::after" {:content (garden.util/wrap-quotes " ")}])
```

Oh, and I've wrapped the selector in quotes instead of using a keyword since this works cross-platform.

**Comment by StarScape** [comment]
I am indeed using ClojureScript. I actually thought it was a bit odd that a leading `.` was a valid keyword, but the compiler did not complain at me so 🤷.

@Outrovurt Thanks for pointing me to the `wrap-quotes` function! That should solve my issue. Closing this.

**Comment by harold** [comment]
Notably the leading dot is fine. It’s the double colon that’s borking it, I think. (:

the leading dot is very convenient for css classes.

**Comment by StarScape** [comment]
Ahh, did not realize, but that makes more sense
