### ISSUE TITLE
Add scaling (%) color functions.

### ISSUE THREAD

**Issue by danneu** [noprompt/garden#26]
Right now, `garden.color`'s [color-update functions](https://github.com/noprompt/garden/blob/master/src/cljx/garden/color.cljx#L267-L290) simply add or subtract a fixed `amount` from the percent value.

It's useful, but sometimes you want to instead scale a value.

For example, darkening `a:hover` by a fixed `15` is more visible when the contrast between your colors are low, and less visible when the contrast happens to be high. 

In such a case, darkening instead by `15%` would create the same aesthetic change regardless of the color scheme.

I've implemented some: https://github.com/danneu/garden-compass/blob/master/src/garden_compass/helpers/colors.clj#L57-L65

- test: https://github.com/danneu/garden-compass/blob/master/test/garden_compass/helpers/colors_test.clj#L18-L22

**Comment by priyatam** [comment]
@danneu are you still interested in adding these utility functions? These seem small enough, and I'm happy to add them.

**Comment by danneu** [comment]
@priyatam go ahead, i haven't worked with clojure in some time.
