### ISSUE TITLE
One parent only child selector

### ISSUE THREAD

**Issue by ccfontes** [noprompt/garden#46]
This example is presented in the README as a way to represent child selectors:

``` clj
(css [:h1 :h2 [:a {:text-decoration "none"]]) ; btw, there is a typo in the README too :}
"h1 a, h2 a{text-decoration:none}"
```

What if I wanted the corresponding CSS to be:

``` clj
"h1, h2 a{text-decoration:none}"
```

instead?

**Comment by ccfontes** [comment]
bump (about my suggestions)

**Comment by noprompt** [comment]
@ccfontes Hey, sorry. I just haven't had enough free time lately to think about Garden. My apologies. It'll probably be a little while before I can start working on it again. `descendant` isn't that bad of a name but I know it's long to type. If you're using it a lot and you really don't like it you can always alias it or patch the ns manually.

**Comment by ccfontes** [comment]
@noprompt `descendant` is the official name for the selector anyway.
