### ISSUE TITLE
with-media DSL

### ISSUE THREAD

**Issue by lsnape** [noprompt/garden#60]
Consider the following example Garden code that changes the h2 font size on screen width:

```
(css
   [:h2 {:font-size (em 10)}]

   (at-media {:min-width (px 480)}
             [[:h2 {:font-size (em 8)}]
              [:p {:margin (px 22)}]])

   (at-media {:min-width (px 980)}
             [[:h2 {:font-size (em 9)}]])

   (at-media {:min-width (px 1024)}
             [[:h2 {:font-size (em 12)}]]))
```

I would like to express the media queries at the value level, rather than at the class level, like this:

```
(with-media {:phone (px 480)
             :tablet (px 980)
             :desktop (px 1024)}

    [:h2 {:font-size (at-least :default (em 10)
                               :desktop (em 12)
                               :tablet (em 9)
                               :phone (em 8))}]

    [:p {:margin (at-least :desktop (px 22))}])
```

I find the latter more concise than the first, and easier to locate a change when I'm tweaking values.

I'm planning to implement something like this anyway.. but wondered if there's room for this kind of functionality in the Garden project?

**Comment by jeluard** [comment]
There is some relevant work in latest media queries spec [1](http://dev.w3.org/csswg/mediaqueries/#mq-ranges) [2](http://dev.w3.org/csswg/mediaqueries/#custom-mq) that can help.

**Comment by noprompt** [comment]
I think this is a good idea but it might be better as a separate library.
