### ISSUE TITLE
stop reversing declaration order

### ISSUE THREAD

**Issue by nchurch** [noprompt/garden#72]
Garden's output CSS puts declarations in the reverse order of the input maps.  Admittedly this is only a cosmetic issue, but it does make debugging (i.e. verifying you got the CSS you were looking for) that much harder.

Presumably this is the convenient way to convert it, but if the cost is not prohibitive, it would be nice to get the output declaration in the same order as the input map.

**Comment by noprompt** [comment]
@nchurch Clojure's maps do not guarantee order and therefore neither does Garden.

```clj
user> {:foo "1" :bar "2" :baz "3"}
{:baz "3", :bar "2", :foo "1"}
```

If you require your declarations to be ordered than use multiple maps (Garden does not restrict this).

**Comment by darwin** [comment]
I have just switched to garden yesterday and I'm the process of converting existing CSS to garden. I like it very much. Thank you @noprompt.

I had similar troubles with maps ordering. For example here:
https://github.com/darwin/faceboard/blob/a33f472c26f42338ec987a6c16e38a23ff7c2b66/frontend/styles/css/tabs.clj#L26-L27

I ended up resolving it with a macro. I transparently turn every map into a sequence of single-item maps and thus preserving their order:
https://github.com/darwin/faceboard/blob/a33f472c26f42338ec987a6c16e38a23ff7c2b66/frontend/styles/lib/helpers.clj#L38

The '>>' macro adds more sugar for my taste. Also made px more general to define multiple values at once.

**Comment by noprompt** [comment]
@darwin You've done some very nice stuff there! The `px` helper is nice. I will have to think of a clean way to fold it back into the mainline along with the work I've done extracting `garden.units` into it's [own project](https://github.com/garden-clojure/garden-units).

**Comment by nchurch** [comment]
Darwin, thanks for the hint, and noprompt, can't believe I forgot about that aspect of Clojure.  (It is a bit of a pain when it comes to things like Hiccup and Garden.)

I also appreciate editing the subject title-----you were able to find a more gracious wording than I came up with.

**Comment by darwin** [comment]
btw. I had to change my solution and instead of maps to use vectors to really preserve the order. Not that big difference.

https://github.com/darwin/faceboard/tree/master/frontend/styles/faceboard/css
https://github.com/darwin/faceboard/blob/4449f559a058b1d0604dd3142527ec6d48d278fd/frontend/styles/faceboard/lib/helpers.clj#L24-L39
