### ISSUE TITLE
Multiple versions of the same property?

### ISSUE THREAD

**Issue by ecarlisle** [noprompt/garden#73]
Hi!
Enjoying using Garden to generate my CSS.  I'm wondering about cases where the same CSS property may be used more than once, usually to account for cross-browser compatibility.  A good example of this case would be for CSS3 background gradients, where the "background: " can be used several times to achieve maximum support.

```
background: #205d8d; /* Old browsers */
background: -moz-linear-gradient(top,  #205d8d 0%, #205d8d 32%, #6c94b4 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#205d8d), color-stop(32%,#205d8d), color-stop(100%,#6c94b4)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  #205d8d 0%,#205d8d 32%,#6c94b4 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  #205d8d 0%,#205d8d 32%,#6c94b4 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  #205d8d 0%,#205d8d 32%,#6c94b4 100%); /* IE10+ */
background: linear-gradient(to bottom,  #205d8d 0%,#205d8d 32%,#6c94b4 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#205d8d', endColorstr='#6c94b4',GradientType=0 ); /* IE6-9 */
```

I can't use multiple keywords, so this approach wouldn't cut it:

```
[:header {
  :background ...
  :background ...
  :background ...
}]
```

I'm fairly new to Clojure, so I'm sorry if there's a solution native to the language. :-)

Best and thank you for your work!
Eric

**Comment by noprompt** [comment]
See the answer [here](https://github.com/noprompt/garden/issues/6#issuecomment-20297639) in #6. Thanks for the positive feedback!

**Comment by ecarlisle** [comment]
Fantastic! Thank you very much for your help!
