### ISSUE TITLE
yuicompressor packages a modified rhino

### ISSUE THREAD

**Issue by bendlas** [noprompt/garden#78]
The yuicompressor dependency adds rhino classes to the classpath. There is an [open PR](https://github.com/yui/yuicompressor/pull/179) for that, but the yuicompressor maintainers don't seem overly hesitant to fix it.

**Comment by bendlas** [comment]
@noprompt sorry, this fix doesn't work. yuicompressor **repackages** rhino. That means, that rhino classes are in the the yuicompressor `.jar`.

**Comment by noprompt** [comment]
I think this is a separate issue in that a solution to this problem, possibly _the_ solution, would be to isolate the compression aspect of Garden in a separate library.

**Comment by priyatam** [comment]
I agree. We should remove all such dependencies and recommend [postscss](http://postcss.org) plugins. Garden can benefit in the long term when we avoid 3rd party deps.

**Comment by jeluard** [comment]
I agree too, I'd rather have garden focus on CSS generation.
