### ISSUE TITLE
nth-child with class selector

### ISSUE THREAD

**Issue by rhacker** [noprompt/garden#90]
Hi guys,
Firstly, thanks for creating this lovely lib so we can work with styling using only clojure datastructure which is awesome.

Secondly, I have a question regarding writing nth-child selector:

```clojure
(def list-striped
  [:&.list--striped
   [(:list-item(s/nth-child :odd)
                  {:background-color "#ccc"}]])

;; =>
ul.list.list--striped .list-item, ul.list.list--striped :nth-child(odd) {
  background-color: #ccc;
}
```

It doesn't seem to generate what I want which is 
```css
ul.list.list--striped .list-item:nth-child(odd) {
  background-color: #ccc;
}
```

And I have another question that in any case we can write just pure css string and integrate it with the system. It would be quick for new dev to get things done with complex selector (designer), then we can move on refactor later.

Thanks

**Comment by noprompt** [comment]
It looks like the second nested rule is missing a `&` reference.

**Comment by rhacker** [comment]
@noprompt I doesn't seem to work either. This is my second try but still, it doesn't seem to work T_T
Using selector is a bit difficult somehow T_T

```
(def list-striped
  [:&.list--striped
   [:.list-item (s/nth-child :odd)
    {:background-color "#ccc"}]])
;; -> 
ul.list.list--striped .list-item, ul.list.list--striped :nth-child(odd) {
  background-color: #ccc;
}
```

**Comment by ernestas** [comment]
This:
```clojure
(garden.core/css [:ul
                  [:&.list
                   [:&.list--striped
                    [(garden.selectors/& (garden.selectors/nth-child :odd))
                     {:background-color "#ccc"}]]]])
```

outputs this:

```
"ul.list.list--striped .list-item:nth-child(odd) {\n  background-color: #ccc;\n}"
```

**Comment by rhacker** [comment]
thanks @ernestas
