### ISSUE TITLE
throw only takes 1 argument

### ISSUE THREAD

**Issue by lnostdal** [noprompt/garden#93]
I think `throw` only takes 1 argument. Clojure 1.7.x doesn't show any error when compiling, but 1.8.x does for this: https://github.com/noprompt/garden/blob/master/src/garden/selectors.cljc#L879

**Comment by noprompt** [comment]
@lnostdal You're right and this is why `throw` was recently patched to validate it's arguments (which makes me wonder how many situations such as this one are floating around). Anyway this looks like a case of the missing `forward-slurp`. Patch welcome.

**Comment by tautr** [comment]
@noprompt Any chance you could push this to Clojars?
